// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatSmileyMessage.xml' the '15/06/2011 01:38:45'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ChatSmileyMessage : Message
	{
		public const uint Id = 801;
		public override uint MessageId
		{
			get
			{
				return 801;
			}
		}
		
		public int entityId;
		public byte smileyId;
		public int accountId;
		
		public ChatSmileyMessage()
		{
		}
		
		public ChatSmileyMessage(int entityId, byte smileyId, int accountId)
		{
			this.entityId = entityId;
			this.smileyId = smileyId;
			this.accountId = accountId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(entityId);
			writer.WriteByte(smileyId);
			writer.WriteInt(accountId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			entityId = reader.ReadInt();
			smileyId = reader.ReadByte();
			if ( smileyId < 0 )
			{
				throw new Exception("Forbidden value on smileyId = " + smileyId + ", it doesn't respect the following condition : smileyId < 0");
			}
			accountId = reader.ReadInt();
			if ( accountId < 0 )
			{
				throw new Exception("Forbidden value on accountId = " + accountId + ", it doesn't respect the following condition : accountId < 0");
			}
		}
	}
}
