// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MoodSmileyRequestMessage.xml' the '15/06/2011 01:38:45'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class MoodSmileyRequestMessage : Message
	{
		public const uint Id = 6192;
		public override uint MessageId
		{
			get
			{
				return 6192;
			}
		}
		
		public byte smileyId;
		
		public MoodSmileyRequestMessage()
		{
		}
		
		public MoodSmileyRequestMessage(byte smileyId)
		{
			this.smileyId = smileyId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(smileyId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			smileyId = reader.ReadByte();
		}
	}
}
