// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NicknameAcceptedMessage.xml' the '22/08/2011 17:22:49'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class NicknameAcceptedMessage : Message
	{
		public const uint Id = 5641;
		public override uint MessageId
		{
			get
			{
				return 5641;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
