// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TrustStatusMessage.xml' the '30/06/2011 11:40:21'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class TrustStatusMessage : Message
	{
		public const uint Id = 6267;
		public override uint MessageId
		{
			get
			{
				return 6267;
			}
		}
		
		public bool trusted;
		
		public TrustStatusMessage()
		{
		}
		
		public TrustStatusMessage(bool trusted)
		{
			this.trusted = trusted;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(trusted);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			trusted = reader.ReadBoolean();
		}
	}
}
