// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GroupMonsterStaticInformations.xml' the '05/11/2011 17:26:02'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Types
{
	public class GroupMonsterStaticInformations
	{
		public const uint Id = 140;
		public virtual short TypeId
		{
			get
			{
				return 140;
			}
		}
		
		public int mainCreatureGenericId;
		public sbyte mainCreatureGrade;
		public IEnumerable<Types.MonsterInGroupInformations> underlings;
		
		public GroupMonsterStaticInformations()
		{
		}
		
		public GroupMonsterStaticInformations(int mainCreatureGenericId, sbyte mainCreatureGrade, IEnumerable<Types.MonsterInGroupInformations> underlings)
		{
			this.mainCreatureGenericId = mainCreatureGenericId;
			this.mainCreatureGrade = mainCreatureGrade;
			this.underlings = underlings;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(mainCreatureGenericId);
			writer.WriteSByte(mainCreatureGrade);
			writer.WriteUShort((ushort)underlings.Count());
			foreach (var entry in underlings)
			{
				entry.Serialize(writer);
			}
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			mainCreatureGenericId = reader.ReadInt();
			mainCreatureGrade = reader.ReadSByte();
			if ( mainCreatureGrade < 0 )
			{
				throw new Exception("Forbidden value on mainCreatureGrade = " + mainCreatureGrade + ", it doesn't respect the following condition : mainCreatureGrade < 0");
			}
			int limit = reader.ReadUShort();
			underlings = new Types.MonsterInGroupInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				(underlings as MonsterInGroupInformations[])[i] = new Types.MonsterInGroupInformations();
				(underlings as Types.MonsterInGroupInformations[])[i].Deserialize(reader);
			}
		}
	}
}
