// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GroupMonsterStaticInformations.xml' the '14/06/2011 11:32:47'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class GroupMonsterStaticInformations
	{
		public const uint Id = 140;
		public short TypeId
		{
			get
			{
				return 140;
			}
		}
		
		public int mainCreatureGenericId;
		public short mainCreaturelevel;
		public Types.MonsterInGroupInformations[] underlings;
		
		public GroupMonsterStaticInformations()
		{
		}
		
		public GroupMonsterStaticInformations(int mainCreatureGenericId, short mainCreaturelevel, Types.MonsterInGroupInformations[] underlings)
		{
			this.mainCreatureGenericId = mainCreatureGenericId;
			this.mainCreaturelevel = mainCreaturelevel;
			this.underlings = underlings;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(mainCreatureGenericId);
			writer.WriteShort(mainCreaturelevel);
			writer.WriteUShort((ushort)underlings.Length);
			for (int i = 0; i < underlings.Length; i++)
			{
				underlings[i].Serialize(writer);
			}
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			mainCreatureGenericId = reader.ReadInt();
			mainCreaturelevel = reader.ReadShort();
			if ( mainCreaturelevel < 0 )
			{
				throw new Exception("Forbidden value on mainCreaturelevel = " + mainCreaturelevel + ", it doesn't respect the following condition : mainCreaturelevel < 0");
			}
			int limit = reader.ReadUShort();
			underlings = new Types.MonsterInGroupInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				underlings[i] = new Types.MonsterInGroupInformations();
				underlings[i].Deserialize(reader);
			}
		}
	}
}
