// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'UpdateMountBoost.xml' the '14/06/2011 11:32:50'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class UpdateMountBoost
	{
		public const uint Id = 356;
		public short TypeId
		{
			get
			{
				return 356;
			}
		}
		
		public byte type;
		
		public UpdateMountBoost()
		{
		}
		
		public UpdateMountBoost(byte type)
		{
			this.type = type;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteByte(type);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			type = reader.ReadByte();
		}
	}
}
