// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlreadyConnectedMessage.xml' the '15/06/2011 01:38:42'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class AlreadyConnectedMessage : Message
	{
		public const uint Id = 109;
		public override uint MessageId
		{
			get
			{
				return 109;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
