// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HelloGameMessage.xml' the '15/06/2011 01:38:42'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class HelloGameMessage : Message
	{
		public const uint Id = 101;
		public override uint MessageId
		{
			get
			{
				return 101;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
