// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SequenceStartMessage.xml' the '24/06/2011 12:04:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class SequenceStartMessage : Message
	{
		public const uint Id = 955;
		public override uint MessageId
		{
			get
			{
				return 955;
			}
		}
		
		public byte sequenceType;
		public int authorId;
		
		public SequenceStartMessage()
		{
		}
		
		public SequenceStartMessage(byte sequenceType, int authorId)
		{
			this.sequenceType = sequenceType;
			this.authorId = authorId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(sequenceType);
			writer.WriteInt(authorId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			sequenceType = reader.ReadByte();
			authorId = reader.ReadInt();
		}
	}
}
