// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HouseInformationsExtended.xml' the '14/06/2011 11:32:49'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class HouseInformationsExtended : HouseInformations
	{
		public const uint Id = 112;
		public short TypeId
		{
			get
			{
				return 112;
			}
		}
		
		public Types.GuildInformations guildInfo;
		
		public HouseInformationsExtended()
		{
		}
		
		public HouseInformationsExtended(int houseId, int[] doorsOnMap, string ownerName, bool isOnSale, short modelId, Types.GuildInformations guildInfo)
			 : base(houseId, doorsOnMap, ownerName, isOnSale, modelId)
		{
			this.guildInfo = guildInfo;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			guildInfo.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			guildInfo = new Types.GuildInformations();
			guildInfo.Deserialize(reader);
		}
	}
}
