// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuidedModeReturnRequestMessage.xml' the '09/12/2011 21:48:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuidedModeReturnRequestMessage : Message
	{
		public const uint Id = 6088;
		public override uint MessageId
		{
			get
			{
				return 6088;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
