// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuidedModeReturnRequestMessage.xml' the '15/06/2011 01:38:55'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuidedModeReturnRequestMessage : Message
	{
		public const uint Id = 6088;
		public override uint MessageId
		{
			get
			{
				return 6088;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
