// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'QuestListMessage.xml' the '24/06/2011 12:04:51'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class QuestListMessage : Message
	{
		public const uint Id = 5626;
		public override uint MessageId
		{
			get
			{
				return 5626;
			}
		}
		
		public short[] finishedQuestsIds;
		public short[] activeQuestsIds;
		
		public QuestListMessage()
		{
		}
		
		public QuestListMessage(short[] finishedQuestsIds, short[] activeQuestsIds)
		{
			this.finishedQuestsIds = finishedQuestsIds;
			this.activeQuestsIds = activeQuestsIds;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)finishedQuestsIds.Length);
			for (int i = 0; i < finishedQuestsIds.Length; i++)
			{
				writer.WriteShort(finishedQuestsIds[i]);
			}
			writer.WriteUShort((ushort)activeQuestsIds.Length);
			for (int i = 0; i < activeQuestsIds.Length; i++)
			{
				writer.WriteShort(activeQuestsIds[i]);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			finishedQuestsIds = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				finishedQuestsIds[i] = reader.ReadShort();
			}
			limit = reader.ReadUShort();
			activeQuestsIds = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				activeQuestsIds[i] = reader.ReadShort();
			}
		}
	}
}
