// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'QuestStepInfoMessage.xml' the '22/08/2011 17:22:57'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class QuestStepInfoMessage : Message
	{
		public const uint Id = 5625;
		public override uint MessageId
		{
			get
			{
				return 5625;
			}
		}
		
		public short questId;
		public short stepId;
		public IEnumerable<short> objectivesIds;
		public IEnumerable<bool> objectivesStatus;
		
		public QuestStepInfoMessage()
		{
		}
		
		public QuestStepInfoMessage(short questId, short stepId, IEnumerable<short> objectivesIds, IEnumerable<bool> objectivesStatus)
		{
			this.questId = questId;
			this.stepId = stepId;
			this.objectivesIds = objectivesIds;
			this.objectivesStatus = objectivesStatus;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(questId);
			writer.WriteShort(stepId);
			writer.WriteUShort((ushort)objectivesIds.Count());
			foreach (var entry in objectivesIds)
			{
				writer.WriteShort(entry);
			}
			writer.WriteUShort((ushort)objectivesStatus.Count());
			foreach (var entry in objectivesStatus)
			{
				writer.WriteBoolean(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			questId = reader.ReadShort();
			if ( questId < 0 )
			{
				throw new Exception("Forbidden value on questId = " + questId + ", it doesn't respect the following condition : questId < 0");
			}
			stepId = reader.ReadShort();
			if ( stepId < 0 )
			{
				throw new Exception("Forbidden value on stepId = " + stepId + ", it doesn't respect the following condition : stepId < 0");
			}
			int limit = reader.ReadUShort();
			objectivesIds = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(objectivesIds as short[])[i] = reader.ReadShort();
			}
			limit = reader.ReadUShort();
			objectivesStatus = new bool[limit];
			for (int i = 0; i < limit; i++)
			{
				(objectivesStatus as bool[])[i] = reader.ReadBoolean();
			}
		}
	}
}
