using System;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Guilds
{
    public class GuildMemberRelator
    {
        public static string FetchQuery = "SELECT * FROM guild_members";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByGuildId =
            "SELECT * FROM guild_members WHERE GuildId={0}";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FindByCharacterId = "SELECT * FROM guild_members WHERE CharacterId={0}";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchCharacterById = "SELECT * FROM characters WHERE Id={0}";
    }

    [TableName("guild_members")]
    public class GuildMemberRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("CharacterId", false)]
        public int CharacterId
        {
            get;
            set;
        }

        public int AccountId
        {
            get;
            set;
        }

        public int GuildId
        {
            get;
            set;
        }

        public short RankId
        {
            get;
            set;
        }

        public GuildRightsBitEnum Rights
        {
            get;
            set;
        }

        public long GivenExperience
        {
            get;
            set;
        }

        public byte GivenPercent
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public byte Level
        {
            get;
            set;
        }

        public PlayableBreedEnum Breed
        {
            get;
            set;
        }

        public SexTypeEnum Sex
        {
            get;
            set;
        }

        public AlignmentSideEnum AlignmentSide
        {
            get;
            set;
        }

        public DateTime LastConnection
        {
            get;
            set;
        }
    }
}
