using System;
using System.Collections.Generic;
using Stump.DofusProtocol.Enums;
using Stump.DofusProtocol.Types;
using Stump.DofusProtocol.Types.Extensions;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Breeds;
using Stump.Server.WorldServer.Game.Maps;

namespace Stump.Server.WorldServer.Database.Guilds
{
    public class GuildMemberRelator
    {
        public static string FetchQuery = "SELECT * FROM guild_members";

        public static string FetchByGuildId =
            "SELECT * FROM guild_members WHERE GuildId={0}";

        public static string FindByCharacterId = "SELECT * FROM guild_members WHERE CharacterId={0}";

        public static string FetchCharacterById = "SELECT * FROM characters WHERE Id={0}";
    }

    [TableName("guild_members")]
    public class GuildMemberRecord : IAutoGeneratedRecord
    {
        public int Id
        {
            get;
            set;
        }

        public int CharacterId
        {
            get;
            set;
        }

        public int AccountId
        {
            get;
            set;
        }

        public int GuildId
        {
            get;
            set;
        }

        public short RankId
        {
            get;
            set;
        }

        public double GivenExperience
        {
            get;
            set;
        }

        public sbyte GivenPercent
        {
            get;
            set;
        }
    }
}
