// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'Preset.xml' the '14/06/2011 11:32:50'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class Preset
	{
		public const uint Id = 355;
		public short TypeId
		{
			get
			{
				return 355;
			}
		}
		
		public byte presetId;
		public byte symbolId;
		public Types.PresetItem[] objects;
		
		public Preset()
		{
		}
		
		public Preset(byte presetId, byte symbolId, Types.PresetItem[] objects)
		{
			this.presetId = presetId;
			this.symbolId = symbolId;
			this.objects = objects;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteByte(presetId);
			writer.WriteByte(symbolId);
			writer.WriteUShort((ushort)objects.Length);
			for (int i = 0; i < objects.Length; i++)
			{
				objects[i].Serialize(writer);
			}
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			presetId = reader.ReadByte();
			if ( presetId < 0 )
			{
				throw new Exception("Forbidden value on presetId = " + presetId + ", it doesn't respect the following condition : presetId < 0");
			}
			symbolId = reader.ReadByte();
			if ( symbolId < 0 )
			{
				throw new Exception("Forbidden value on symbolId = " + symbolId + ", it doesn't respect the following condition : symbolId < 0");
			}
			int limit = reader.ReadUShort();
			objects = new Types.PresetItem[limit];
			for (int i = 0; i < limit; i++)
			{
				objects[i] = new Types.PresetItem();
				objects[i].Deserialize(reader);
			}
		}
	}
}
