// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightTeamMemberMonsterInformations.xml' the '14/06/2011 11:32:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class FightTeamMemberMonsterInformations : FightTeamMemberInformations
	{
		public const uint Id = 6;
		public short TypeId
		{
			get
			{
				return 6;
			}
		}
		
		public int monsterId;
		public byte grade;
		
		public FightTeamMemberMonsterInformations()
		{
		}
		
		public FightTeamMemberMonsterInformations(int id, int monsterId, byte grade)
			 : base(id)
		{
			this.monsterId = monsterId;
			this.grade = grade;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(monsterId);
			writer.WriteByte(grade);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			monsterId = reader.ReadInt();
			grade = reader.ReadByte();
			if ( grade < 0 )
			{
				throw new Exception("Forbidden value on grade = " + grade + ", it doesn't respect the following condition : grade < 0");
			}
		}
	}
}
