// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightTeamInformations.xml' the '14/06/2011 11:32:46'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class FightTeamInformations : AbstractFightTeamInformations
	{
		public const uint Id = 33;
		public short TypeId
		{
			get
			{
				return 33;
			}
		}
		
		public Types.FightTeamMemberInformations[] teamMembers;
		
		public FightTeamInformations()
		{
		}
		
		public FightTeamInformations(byte teamId, int leaderId, byte teamSide, byte teamTypeId, Types.FightTeamMemberInformations[] teamMembers)
			 : base(teamId, leaderId, teamSide, teamTypeId)
		{
			this.teamMembers = teamMembers;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUShort((ushort)teamMembers.Length);
			for (int i = 0; i < teamMembers.Length; i++)
			{
				writer.WriteShort(teamMembers[i].TypeId);
				teamMembers[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			int limit = reader.ReadUShort();
			teamMembers = new Types.FightTeamMemberInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				teamMembers[i] = ProtocolTypeManager.GetInstance<Types.FightTeamMemberInformations>(reader.ReadShort());
				teamMembers[i].Deserialize(reader);
			}
		}
	}
}
