// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightCharacterInformations.xml' the '14/06/2011 11:32:46'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class GameFightCharacterInformations : GameFightFighterNamedInformations
	{
		public const uint Id = 46;
		public short TypeId
		{
			get
			{
				return 46;
			}
		}
		
		public short level;
		public Types.ActorAlignmentInformations alignmentInfos;
		
		public GameFightCharacterInformations()
		{
		}
		
		public GameFightCharacterInformations(int contextualId, Types.EntityLook look, Types.EntityDispositionInformations disposition, byte teamId, bool alive, Types.GameFightMinimalStats stats, string name, short level, Types.ActorAlignmentInformations alignmentInfos)
			 : base(contextualId, look, disposition, teamId, alive, stats, name)
		{
			this.level = level;
			this.alignmentInfos = alignmentInfos;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(level);
			alignmentInfos.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			level = reader.ReadShort();
			if ( level < 0 )
			{
				throw new Exception("Forbidden value on level = " + level + ", it doesn't respect the following condition : level < 0");
			}
			alignmentInfos = new Types.ActorAlignmentInformations();
			alignmentInfos.Deserialize(reader);
		}
	}
}
