// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutBarRemoveRequestMessage.xml' the '30/06/2011 11:40:21'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ShortcutBarRemoveRequestMessage : Message
	{
		public const uint Id = 6228;
		public override uint MessageId
		{
			get
			{
				return 6228;
			}
		}
		
		public byte barType;
		public int slot;
		
		public ShortcutBarRemoveRequestMessage()
		{
		}
		
		public ShortcutBarRemoveRequestMessage(byte barType, int slot)
		{
			this.barType = barType;
			this.slot = slot;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(barType);
			writer.WriteInt(slot);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			barType = reader.ReadByte();
			if ( barType < 0 )
			{
				throw new Exception("Forbidden value on barType = " + barType + ", it doesn't respect the following condition : barType < 0");
			}
			slot = reader.ReadInt();
			if ( slot < 0 || slot > 99 )
			{
				throw new Exception("Forbidden value on slot = " + slot + ", it doesn't respect the following condition : slot < 0 || slot > 99");
			}
		}
	}
}
