// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StorageObjectsUpdateMessage.xml' the '24/06/2011 12:04:56'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class StorageObjectsUpdateMessage : Message
	{
		public const uint Id = 6036;
		public override uint MessageId
		{
			get
			{
				return 6036;
			}
		}
		
		public Types.ObjectItem[] objectList;
		
		public StorageObjectsUpdateMessage()
		{
		}
		
		public StorageObjectsUpdateMessage(Types.ObjectItem[] objectList)
		{
			this.objectList = objectList;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectList.Length);
			for (int i = 0; i < objectList.Length; i++)
			{
				objectList[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectList = new Types.ObjectItem[limit];
			for (int i = 0; i < limit; i++)
			{
				objectList[i] = new Types.ObjectItem();
				objectList[i].Deserialize(reader);
			}
		}
	}
}
