// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StorageObjectUpdateMessage.xml' the '05/11/2011 17:25:59'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class StorageObjectUpdateMessage : Message
	{
		public const uint Id = 5647;
		public override uint MessageId
		{
			get
			{
				return 5647;
			}
		}
		
		public Types.ObjectItem @object;
		
		public StorageObjectUpdateMessage()
		{
		}
		
		public StorageObjectUpdateMessage(Types.ObjectItem @object)
		{
			this.@object = @object;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			@object.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			@object = new Types.ObjectItem();
			@object.Deserialize(reader);
		}
	}
}
