// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MapInformationsRequestMessage.xml' the '05/11/2011 17:25:50'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class MapInformationsRequestMessage : Message
	{
		public const uint Id = 225;
		public override uint MessageId
		{
			get
			{
				return 225;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
