// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IdentificationFailedBannedMessage.xml' the '30/06/2011 11:40:08'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class IdentificationFailedBannedMessage : IdentificationFailedMessage
	{
		public const uint Id = 6174;
		public override uint MessageId
		{
			get
			{
				return 6174;
			}
		}
		
		public int duration;
		
		public IdentificationFailedBannedMessage()
		{
		}
		
		public IdentificationFailedBannedMessage(byte reason, int duration)
			 : base(reason)
		{
			this.duration = duration;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(duration);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			duration = reader.ReadInt();
			if ( duration < 0 )
			{
				throw new Exception("Forbidden value on duration = " + duration + ", it doesn't respect the following condition : duration < 0");
			}
		}
	}
}
