// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionFightInvisibilityMessage.xml' the '24/06/2011 12:04:45'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameActionFightInvisibilityMessage : AbstractGameActionMessage
	{
		public const uint Id = 5821;
		public override uint MessageId
		{
			get
			{
				return 5821;
			}
		}
		
		public int targetId;
		public byte state;
		
		public GameActionFightInvisibilityMessage()
		{
		}
		
		public GameActionFightInvisibilityMessage(short actionId, int sourceId, int targetId, byte state)
			 : base(actionId, sourceId)
		{
			this.targetId = targetId;
			this.state = state;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(targetId);
			writer.WriteByte(state);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			targetId = reader.ReadInt();
			state = reader.ReadByte();
		}
	}
}
