// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'EmoteRemoveMessage.xml' the '30/06/2011 11:40:13'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class EmoteRemoveMessage : Message
	{
		public const uint Id = 5687;
		public override uint MessageId
		{
			get
			{
				return 5687;
			}
		}
		
		public byte emoteId;
		
		public EmoteRemoveMessage()
		{
		}
		
		public EmoteRemoveMessage(byte emoteId)
		{
			this.emoteId = emoteId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(emoteId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			emoteId = reader.ReadByte();
			if ( emoteId < 0 )
			{
				throw new Exception("Forbidden value on emoteId = " + emoteId + ", it doesn't respect the following condition : emoteId < 0");
			}
		}
	}
}
