// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightReadyMessage.xml' the '15/06/2011 01:38:47'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameFightReadyMessage : Message
	{
		public const uint Id = 708;
		public override uint MessageId
		{
			get
			{
				return 708;
			}
		}
		
		public bool isReady;
		
		public GameFightReadyMessage()
		{
		}
		
		public GameFightReadyMessage(bool isReady)
		{
			this.isReady = isReady;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(isReady);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			isReady = reader.ReadBoolean();
		}
	}
}
