// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightTurnReadyRequestMessage.xml' the '15/06/2011 01:38:48'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameFightTurnReadyRequestMessage : Message
	{
		public const uint Id = 715;
		public override uint MessageId
		{
			get
			{
				return 715;
			}
		}
		
		public int id;
		
		public GameFightTurnReadyRequestMessage()
		{
		}
		
		public GameFightTurnReadyRequestMessage(int id)
		{
			this.id = id;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(id);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			id = reader.ReadInt();
		}
	}
}
