// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'RawDataMessage.xml' the '30/06/2011 11:40:21'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class RawDataMessage : Message
	{
		public const uint Id = 6253;
		public override uint MessageId
		{
			get
			{
				return 6253;
			}
		}
		
		public IEnumerable<byte> content;
		
		public RawDataMessage()
		{
		}
		
		public RawDataMessage(IEnumerable<byte> content)
		{
			this.content = content;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)content.Count());
			foreach (var entry in content)
			{
				writer.WriteByte(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			content = new byte[limit];
			for (int i = 0; i < limit; i++)
			{
				(content as byte[])[i] = reader.ReadByte();
			}
		}
	}
}
