// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectEffectString.xml' the '14/06/2011 11:32:49'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class ObjectEffectString : ObjectEffect
	{
		public const uint Id = 74;
		public short TypeId
		{
			get
			{
				return 74;
			}
		}
		
		public string value;
		
		public ObjectEffectString()
		{
		}
		
		public ObjectEffectString(short actionId, string value)
			 : base(actionId)
		{
			this.value = value;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUTF(value);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			value = reader.ReadUTF();
		}
	}
}
