// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharactersListMessage.xml' the '15/06/2011 01:38:43'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class CharactersListMessage : Message
	{
		public const uint Id = 151;
		public override uint MessageId
		{
			get
			{
				return 151;
			}
		}
		
		public bool hasStartupActions;
		public Types.CharacterBaseInformations[] characters;
		
		public CharactersListMessage()
		{
		}
		
		public CharactersListMessage(bool hasStartupActions, Types.CharacterBaseInformations[] characters)
		{
			this.hasStartupActions = hasStartupActions;
			this.characters = characters;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(hasStartupActions);
			writer.WriteUShort((ushort)characters.Length);
			for (int i = 0; i < characters.Length; i++)
			{
				writer.WriteShort(characters[i].TypeId);
				characters[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			hasStartupActions = reader.ReadBoolean();
			int limit = reader.ReadUShort();
			characters = new Types.CharacterBaseInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				characters[i] = Types.ProtocolTypeManager.GetInstance<Types.CharacterBaseInformations>(reader.ReadShort());
				characters[i].Deserialize(reader);
			}
		}
	}
}
