// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterSelectedForceReadyMessage.xml' the '15/06/2011 01:38:43'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class CharacterSelectedForceReadyMessage : Message
	{
		public const uint Id = 6072;
		public override uint MessageId
		{
			get
			{
				return 6072;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
