// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'LeaveDialogMessage.xml' the '03/10/2011 12:47:02'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class LeaveDialogMessage : Message
	{
		public const uint Id = 5502;
		public override uint MessageId
		{
			get
			{
				return 5502;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
