using System.Data.Entity.ModelConfiguration;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database
{
    public class ExperienceTableRelator
    {
        public static string FetchQuery = "SELECT * FROM experiences";
    }

    [TableName("experiences")]
    public class ExperienceTableEntry : IAutoGeneratedRecord
    {
        // Primitive properties

        public byte Level
        {
            get;
            set;
        }

        public long? CharacterExp
        {
            get;
            set;
        }

        public long? GuildExp
        {
            get;
            set;
        }

        public long? MountExp
        {
            get;
            set;
        }

        public int? AlignmentHonor
        {
            get;
            set;
        }
    }
}