// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterToRecolorInformation.xml' the '14/06/2011 11:32:45'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class CharacterToRecolorInformation
	{
		public const uint Id = 212;
		public short TypeId
		{
			get
			{
				return 212;
			}
		}
		
		public int id;
		public int[] colors;
		
		public CharacterToRecolorInformation()
		{
		}
		
		public CharacterToRecolorInformation(int id, int[] colors)
		{
			this.id = id;
			this.colors = colors;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(id);
			writer.WriteUShort((ushort)colors.Length);
			for (int i = 0; i < colors.Length; i++)
			{
				writer.WriteInt(colors[i]);
			}
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			id = reader.ReadInt();
			if ( id < 0 )
			{
				throw new Exception("Forbidden value on id = " + id + ", it doesn't respect the following condition : id < 0");
			}
			int limit = reader.ReadUShort();
			colors = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				colors[i] = reader.ReadInt();
			}
		}
	}
}
