using System;
using System.Xml.Serialization;

namespace Stump.Server.BaseServer.IPC.Objects
{
    [Serializable]
    public class WorldServerData
    {
        #region Properties

        /// <summary>
        ///   Internally assigned unique Id of this World.
        /// </summary>
        public int Id;

        /// <summary>
        ///   World address.
        /// </summary>
        public string Address;

        public ushort Port;

        /// <summary>
        ///   World name.
        /// </summary>
        public string Name;

        /// <summary>
        /// Password is generated by server
        /// </summary>
        public string Password;

        public string AddressString
        {
            get { return Address + ":" + Port; }
        }

        #endregion
    }
}