// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameMapChangeOrientationRequestMessage.xml' the '24/06/2011 12:04:48'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameMapChangeOrientationRequestMessage : Message
	{
		public const uint Id = 945;
		public override uint MessageId
		{
			get
			{
				return 945;
			}
		}
		
		public byte direction;
		
		public GameMapChangeOrientationRequestMessage()
		{
		}
		
		public GameMapChangeOrientationRequestMessage(byte direction)
		{
			this.direction = direction;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(direction);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			direction = reader.ReadByte();
			if ( direction < 0 )
			{
				throw new Exception("Forbidden value on direction = " + direction + ", it doesn't respect the following condition : direction < 0");
			}
		}
	}
}
