// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameEntityDispositionMessage.xml' the '03/10/2011 12:46:56'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameEntityDispositionMessage : Message
	{
		public const uint Id = 5693;
		public override uint MessageId
		{
			get
			{
				return 5693;
			}
		}
		
		public Types.IdentifiedEntityDispositionInformations disposition;
		
		public GameEntityDispositionMessage()
		{
		}
		
		public GameEntityDispositionMessage(Types.IdentifiedEntityDispositionInformations disposition)
		{
			this.disposition = disposition;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			disposition.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			disposition = new Types.IdentifiedEntityDispositionInformations();
			disposition.Deserialize(reader);
		}
	}
}
