// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameContextCreateMessage.xml' the '15/06/2011 01:38:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameContextCreateMessage : Message
	{
		public const uint Id = 200;
		public override uint MessageId
		{
			get
			{
				return 200;
			}
		}
		
		public byte context;
		
		public GameContextCreateMessage()
		{
		}
		
		public GameContextCreateMessage(byte context)
		{
			this.context = context;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(context);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			context = reader.ReadByte();
			if ( context < 0 )
			{
				throw new Exception("Forbidden value on context = " + context + ", it doesn't respect the following condition : context < 0");
			}
		}
	}
}
