// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameMapChangeOrientationsMessage.xml' the '15/06/2011 01:38:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameMapChangeOrientationsMessage : Message
	{
		public const uint Id = 6155;
		public override uint MessageId
		{
			get
			{
				return 6155;
			}
		}
		
		public Types.ActorOrientation[] orientations;
		
		public GameMapChangeOrientationsMessage()
		{
		}
		
		public GameMapChangeOrientationsMessage(Types.ActorOrientation[] orientations)
		{
			this.orientations = orientations;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)orientations.Length);
			for (int i = 0; i < orientations.Length; i++)
			{
				orientations[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			orientations = new Types.ActorOrientation[limit];
			for (int i = 0; i < limit; i++)
			{
				orientations[i] = new Types.ActorOrientation();
				orientations[i].Deserialize(reader);
			}
		}
	}
}
