// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChannelEnablingMessage.xml' the '15/06/2011 01:38:45'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ChannelEnablingMessage : Message
	{
		public const uint Id = 890;
		public override uint MessageId
		{
			get
			{
				return 890;
			}
		}
		
		public byte channel;
		public bool enable;
		
		public ChannelEnablingMessage()
		{
		}
		
		public ChannelEnablingMessage(byte channel, bool enable)
		{
			this.channel = channel;
			this.enable = enable;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(channel);
			writer.WriteBoolean(enable);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			channel = reader.ReadByte();
			if ( channel < 0 )
			{
				throw new Exception("Forbidden value on channel = " + channel + ", it doesn't respect the following condition : channel < 0");
			}
			enable = reader.ReadBoolean();
		}
	}
}
