// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FighterStatsListMessage.xml' the '26/06/2012 18:47:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class FighterStatsListMessage : Message
	{
		public const uint Id = 6322;
		public override uint MessageId
		{
			get
			{
				return 6322;
			}
		}
		
		public Types.CharacterCharacteristicsInformations stats;
		
		public FighterStatsListMessage()
		{
		}
		
		public FighterStatsListMessage(Types.CharacterCharacteristicsInformations stats)
		{
			this.stats = stats;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			stats.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			stats = new Types.CharacterCharacteristicsInformations();
			stats.Deserialize(reader);
		}
	}
}
