// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChallengeResultMessage.xml' the '15/06/2011 01:38:48'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ChallengeResultMessage : Message
	{
		public const uint Id = 6019;
		public override uint MessageId
		{
			get
			{
				return 6019;
			}
		}
		
		public byte challengeId;
		public bool success;
		
		public ChallengeResultMessage()
		{
		}
		
		public ChallengeResultMessage(byte challengeId, bool success)
		{
			this.challengeId = challengeId;
			this.success = success;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(challengeId);
			writer.WriteBoolean(success);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			challengeId = reader.ReadByte();
			if ( challengeId < 0 )
			{
				throw new Exception("Forbidden value on challengeId = " + challengeId + ", it doesn't respect the following condition : challengeId < 0");
			}
			success = reader.ReadBoolean();
		}
	}
}
