using System.Data.Entity.ModelConfiguration;
using Castle.ActiveRecord;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database
{
    public class JobRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_jobs";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_jobs WHERE OwnerId={0}";
    }

    [TableName("characters_jobs")]
    public class JobRecord : IAutoGeneratedRecord
    {
        public int JobId
        {
            get;
            set;
        }

        public int OwnerId
        {
            get;
            set;
        }

        public long Experience
        {
            get;
            set;
        }
    }
}