using Stump.Core.IO;
using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Jobs
{
    [TableName("jobs_templates")]
    [D2OClass("Job", "com.ankamagames.dofus.datacenter.jobs")]
    public class JobTemplate : ISaveIntercepter, IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;
        private int[] m_toolIds;
        private string m_toolIdsCSV;

        public int Id
        {
            get;
            set;
        }

        public uint NameId
        {
            get;
            set;
        }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
        }

        public int SpecializationOfId
        {
            get;
            set;
        }

        public int IconId
        {
            get;
            set;
        }

        public string ToolIdsCSV
        {
            get { return m_toolIdsCSV; }
            set
            {
                m_toolIdsCSV = value;
                m_toolIds = value.FromCSV<int>(",");
            }
        }

        [Ignore]
        public int[] ToolIds
        {
            get { return m_toolIds; }
            set
            {
                m_toolIds = value;
                m_toolIdsCSV = value.ToCSV(",");
            }
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var job = (Job) d2oObject;
            Id = job.id;
            NameId = job.nameId;
            SpecializationOfId = job.specializationOfId;
            IconId = job.iconId;
            ToolIds = job.toolIds.ToArray();
        }

        #endregion

        #region ISaveIntercepter Members

        public void BeforeSave(bool insert)
        {
            m_toolIdsCSV = m_toolIds.ToCSV(",");
        }

        #endregion
    }
}