// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatServerMessage.xml' the '30/06/2011 11:40:11'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ChatServerMessage : ChatAbstractServerMessage
	{
		public const uint Id = 881;
		public override uint MessageId
		{
			get
			{
				return 881;
			}
		}
		
		public int senderId;
		public string senderName;
		public int senderAccountId;
		
		public ChatServerMessage()
		{
		}
		
		public ChatServerMessage(byte channel, string content, int timestamp, string fingerprint, int senderId, string senderName, int senderAccountId)
			 : base(channel, content, timestamp, fingerprint)
		{
			this.senderId = senderId;
			this.senderName = senderName;
			this.senderAccountId = senderAccountId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(senderId);
			writer.WriteUTF(senderName);
			writer.WriteInt(senderAccountId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			senderId = reader.ReadInt();
			senderName = reader.ReadUTF();
			senderAccountId = reader.ReadInt();
		}
	}
}
