//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stump.Tools.ClientPatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stump.Tools.ClientPatcher.LangFile", typeof(LangFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access dofus file. Maybe is dofus already open ?.
        /// </summary>
        internal static string Cannot_access_dofus_file {
            get {
                return ResourceManager.GetString("Cannot_access_dofus_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear cache ! Please clear it manually.
        /// </summary>
        internal static string Cannot_clear_cache {
            get {
                return ResourceManager.GetString("Cannot_clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch applied !.
        /// </summary>
        internal static string Patch_applied {
            get {
                return ResourceManager.GetString("Patch_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch removed !.
        /// </summary>
        internal static string Patch_removed {
            get {
                return ResourceManager.GetString("Patch_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dofus path not defined.
        /// </summary>
        internal static string Path_not_defined {
            get {
                return ResourceManager.GetString("Path_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy patch applied !.
        /// </summary>
        internal static string Proxy_patch_applied {
            get {
                return ResourceManager.GetString("Proxy_patch_applied", resourceCulture);
            }
        }
    }
}
