-- EXECUTE ON:breeds

UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '55', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 324, FemaleGhostBonesId = 325 WHERE Id = 1;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 326, FemaleGhostBonesId = 327 WHERE Id = 2;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '120', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 339, FemaleGhostBonesId = 340 WHERE Id = 3;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 341, FemaleGhostBonesId = 328 WHERE Id = 4;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '55', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 329, FemaleGhostBonesId = 342 WHERE Id = 5;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 330, FemaleGhostBonesId = 343 WHERE Id = 6;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 344, FemaleGhostBonesId = 345 WHERE Id = 7;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 331, FemaleGhostBonesId = 346 WHERE Id = 8;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 347, FemaleGhostBonesId = 332 WHERE Id = 9;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 348, FemaleGhostBonesId = 333 WHERE Id = 10;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 349, FemaleGhostBonesId = 334 WHERE Id = 11;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '46', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 350, FemaleGhostBonesId = 351 WHERE Id = 12;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 0, FemaleGhostBonesId = 0 WHERE Id = 13;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 0, FemaleGhostBonesId = 0 WHERE Id = 14;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '50', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 0, FemaleGhostBonesId = 0 WHERE Id = 15;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '55', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 0, FemaleGhostBonesId = 0 WHERE Id = 16;
UPDATE breeds SET StartCell = '283', StartDirection = '1', StartActionPoints = '6', StartMovementPoints = '3', StartHealthPoint = '55', StartProspection = '100', StartLevel = 1, TombBonesId = 23, MaleGhostBonesId = 0, FemaleGhostBonesId = 0 WHERE Id = 17;