// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlignmentSideEnum.as' the '14/06/2011 11:32:51'

namespace Stump.DofusProtocol.Enums
{
	public enum AlignmentSideEnum
	{
		ALIGNMENT_UNKNOWN = -2,
		ALIGNMENT_WITHOUT = -1,
		ALIGNMENT_NEUTRAL = 0,
		ALIGNMENT_ANGEL = 1,
		ALIGNMENT_EVIL = 2,
		ALIGNMENT_MERCENARY = 3,
	}
}
