// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BuildTypeEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum BuildTypeEnum
	{
		RELEASE = 0,
		BETA = 1,
		ALPHA = 2,
		INTERNALTEST = 3,
		NIGHTLYBUILD = 4,
		DEBUG = 5,
	}
}
