// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ClientTechnologyEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum ClientTechnologyEnum
	{
		CLIENT_TECHNOLOGY_UNKNOWN = 0,
		CLIENT_AIR = 1,
		CLIENT_FLASH = 2,
	}
}
