// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CompassTypeEnum.as' the '14/06/2011 11:32:51'

namespace Stump.DofusProtocol.Enums
{
	public enum CompassTypeEnum
	{
		COMPASS_TYPE_SIMPLE = 0,
		COMPASS_TYPE_SPOUSE = 1,
		COMPASS_TYPE_PARTY = 2,
		COMPASS_TYPE_PVP_SEEK = 3,
		COMPASS_TYPE_QUEST = 4,
	}
}
