// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ConsoleMessageTypeEnum.as' the '07/12/2011 16:00:35'

namespace Stump.DofusProtocol.Enums
{
	public enum ConsoleMessageTypeEnum
	{
		CONSOLE_TEXT_MESSAGE = 0,
		CONSOLE_INFO_MESSAGE = 1,
		CONSOLE_ERR_MESSAGE = 2,
	}
}
