// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CraftResultEnum.as' the '24/06/2011 12:00:27'

namespace Stump.DofusProtocol.Enums
{
	public enum CraftResultEnum
	{
		CRAFT_IMPOSSIBLE = 0,
		CRAFT_FAILED = 1,
		CRAFT_SUCCESS = 2,
		CRAFT_NEUTRAL = 3,
	}
}
