// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CraftResultEnum.as' the '07/12/2011 16:00:35'

namespace Stump.DofusProtocol.Enums
{
	public enum CraftResultEnum
	{
		CRAFT_IMPOSSIBLE = 0,
		CRAFT_FAILED = 1,
		CRAFT_SUCCESS = 2,
		CRAFT_NEUTRAL = 3,
	}
}
