// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DebugLevelEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum DebugLevelEnum
	{
		LEVEL_TRACE = 0,
		LEVEL_DEBUG = 1,
		LEVEL_INFO = 2,
		LEVEL_WARN = 3,
		LEVEL_ERROR = 4,
		LEVEL_FATAL = 5,
	}
}
