// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeReplayStopReasonEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum ExchangeReplayStopReasonEnum
	{
		STOPPED_REASON_OK = 1,
		STOPPED_REASON_USER = 2,
		STOPPED_REASON_MISSING_RESSOURCE = 3,
		STOPPED_REASON_IMPOSSIBLE_CRAFT = 4,
	}
}
