// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightOutcomeEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum FightOutcomeEnum
	{
		RESULT_LOST = 0,
		RESULT_DRAW = 1,
		RESULT_VICTORY = 2,
		RESULT_TAX = 5,
		RESULT_DEFENDER_GROUP = 6,
	}
}
