// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightDispellableEnum.as' the '14/06/2011 11:32:51'

namespace Stump.DofusProtocol.Enums
{
	public enum FightDispellableEnum
	{
		DISPELLABLE = 1,
		DISPELLABLE_BY_DEATH = 2,
		NOT_DISPELLABLE = 3,
	}
}
