// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightDispellableEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum FightDispellableEnum
	{
		DISPELLABLE = 1,
		DISPELLABLE_BY_DEATH = 2,
		NOT_DISPELLABLE = 3,
	}
}
