// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionMarkTypeEnum.as' the '24/06/2011 12:00:27'

namespace Stump.DofusProtocol.Enums
{
	public enum GameActionMarkTypeEnum
	{
		GLYPH = 1,
		TRAP = 2,
		WALL = 3,
	}
}
