// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionFightInvisibilityStateEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum GameActionFightInvisibilityStateEnum
	{
		INVISIBLE = 1,
		DETECTED = 2,
		VISIBLE = 3,
	}
}
