// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionMarkTypeEnum.as' the '07/12/2011 16:00:35'

namespace Stump.DofusProtocol.Enums
{
	public enum GameActionMarkTypeEnum
	{
		GLYPH = 1,
		TRAP = 2,
		WALL = 3,
	}
}
