// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayNpcQuestFlagEnum.as' the '07/12/2011 16:00:35'

namespace Stump.DofusProtocol.Enums
{
	public enum GameRolePlayNpcQuestFlagEnum
	{
		QUEST_FLAG_NONE = 0,
		QUEST_FLAG_VALID = 1,
		QUEST_FLAG_START = 2,
	}
}
