// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameHierarchyEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum GameHierarchyEnum
	{
		PLAYER = 0,
		MODERATOR = 10,
		GAMEMASTER_PADAWAN = 20,
		GAMEMASTER = 30,
		ADMIN = 40,
	}
}
