// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountEquipedErrorEnum.as' the '24/06/2011 12:00:27'

namespace Stump.DofusProtocol.Enums
{
	public enum MountEquipedErrorEnum
	{
		UNSET = 0,
		SET = 1,
		RIDING = 2,
	}
}
