// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountEquipedErrorEnum.as' the '07/12/2011 16:00:35'

namespace Stump.DofusProtocol.Enums
{
	public enum MountEquipedErrorEnum
	{
		UNSET = 0,
		SET = 1,
		RIDING = 2,
	}
}
