// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PlayerStateEnum.as' the '07/12/2011 16:00:36'

namespace Stump.DofusProtocol.Enums
{
	public enum PlayerStateEnum
	{
		NOT_CONNECTED = 0,
		GAME_TYPE_ROLEPLAY = 1,
		GAME_TYPE_FIGHT = 2,
		UNKNOWN_STATE = 99,
	}
}
