// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PresetSaveResultEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum PresetSaveResultEnum
	{
		PRESET_SAVE_OK = 1,
		PRESET_SAVE_ERR_UNKNOWN = 2,
		PRESET_SAVE_ERR_TOO_MANY = 3,
	}
}
