// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutBarEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum ShortcutBarEnum
	{
		OBJECT = 0,
		SPELL = 1,
	}
}
