// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SocialContactCategoryEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum SocialContactCategoryEnum
	{
		SOCIAL_CONTACT_FRIEND = 0,
		SOCIAL_CONTACT_SPOUSE = 1,
		SOCIAL_CONTACT_PARTY = 2,
		SOCIAL_CONTACT_GUILD = 3,
		SOCIAL_CONTACT_CRAFTER = 4,
	}
}
