// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeamEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum TeamEnum
	{
		TEAM_CHALLENGER = 0,
		TEAM_DEFENDER = 1,
		TEAM_SPECTATOR = 2,
	}
}
