// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeamTypeEnum.as' the '26/06/2012 18:48:04'

namespace Stump.DofusProtocol.Enums
{
	public enum TeamTypeEnum
	{
		TEAM_TYPE_PLAYER = 0,
		TEAM_TYPE_MONSTER = 1,
		TEAM_TYPE_MUTANT = 2,
		TEAM_TYPE_TAXCOLLECTOR = 3,
		TEAM_TYPE_BAD_PLAYER = 4,
	}
}
