// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'UpdatableMountBoostEnum.as' the '03/10/2011 12:47:13'

namespace Stump.DofusProtocol.Enums
{
	public enum UpdatableMountBoostEnum
	{
		STAMINA = 3,
		MATURITY = 5,
		ENERGY = 1,
		SERENITY = 2,
		LOVE = 4,
		TIREDNESS = 6,
	}
}
