// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AdditionalTaxCollectorInformations.xml' the '09/12/2011 21:48:40'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class AdditionalTaxCollectorInformations
	{
		public const uint Id = 165;
		public virtual short TypeId
		{
			get
			{
				return 165;
			}
		}
		
		public string CollectorCallerName;
		public int date;
		
		public AdditionalTaxCollectorInformations()
		{
		}
		
		public AdditionalTaxCollectorInformations(string CollectorCallerName, int date)
		{
			this.CollectorCallerName = CollectorCallerName;
			this.date = date;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(CollectorCallerName);
			writer.WriteInt(date);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			CollectorCallerName = reader.ReadUTF();
			date = reader.ReadInt();
			if ( date < 0 )
			{
				throw new Exception("Forbidden value on date = " + date + ", it doesn't respect the following condition : date < 0");
			}
		}
	}
}
