// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CompassResetMessage.xml' the '24/06/2011 12:04:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class CompassResetMessage : Message
	{
		public const uint Id = 5584;
		public override uint MessageId
		{
			get
			{
				return 5584;
			}
		}
		
		public byte type;
		
		public CompassResetMessage()
		{
		}
		
		public CompassResetMessage(byte type)
		{
			this.type = type;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(type);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			type = reader.ReadByte();
			if ( type < 0 )
			{
				throw new Exception("Forbidden value on type = " + type + ", it doesn't respect the following condition : type < 0");
			}
		}
	}
}
