// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayGameOverMessage.xml' the '05/11/2011 17:25:50'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameRolePlayGameOverMessage : Message
	{
		public const uint Id = 746;
		public override uint MessageId
		{
			get
			{
				return 746;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
