// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicWhoIsNoMatchMessage.xml' the '24/06/2011 12:04:47'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class BasicWhoIsNoMatchMessage : Message
	{
		public const uint Id = 179;
		public override uint MessageId
		{
			get
			{
				return 179;
			}
		}
		
		public string search;
		
		public BasicWhoIsNoMatchMessage()
		{
		}
		
		public BasicWhoIsNoMatchMessage(string search)
		{
			this.search = search;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(search);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			search = reader.ReadUTF();
		}
	}
}
