// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicSetAwayModeRequestMessage.xml' the '26/06/2012 18:47:46'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class BasicSetAwayModeRequestMessage : Message
	{
		public const uint Id = 5665;
		public override uint MessageId
		{
			get
			{
				return 5665;
			}
		}
		
		public bool enable;
		public bool invisible;
		
		public BasicSetAwayModeRequestMessage()
		{
		}
		
		public BasicSetAwayModeRequestMessage(bool enable, bool invisible)
		{
			this.enable = enable;
			this.invisible = invisible;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			byte flag1 = 0;
			flag1 = BooleanByteWrapper.SetFlag(flag1, 0, enable);
			flag1 = BooleanByteWrapper.SetFlag(flag1, 1, invisible);
			writer.WriteByte(flag1);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			byte flag1 = reader.ReadByte();
			enable = BooleanByteWrapper.GetFlag(flag1, 0);
			invisible = BooleanByteWrapper.GetFlag(flag1, 1);
		}
	}
}
