// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TextInformationMessage.xml' the '30/06/2011 11:40:10'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class TextInformationMessage : Message
	{
		public const uint Id = 780;
		public override uint MessageId
		{
			get
			{
				return 780;
			}
		}
		
		public byte msgType;
		public short msgId;
		public IEnumerable<string> parameters;
		
		public TextInformationMessage()
		{
		}
		
		public TextInformationMessage(byte msgType, short msgId, IEnumerable<string> parameters)
		{
			this.msgType = msgType;
			this.msgId = msgId;
			this.parameters = parameters;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(msgType);
			writer.WriteShort(msgId);
			writer.WriteUShort((ushort)parameters.Count());
			foreach (var entry in parameters)
			{
				writer.WriteUTF(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			msgType = reader.ReadByte();
			if ( msgType < 0 )
			{
				throw new Exception("Forbidden value on msgType = " + msgType + ", it doesn't respect the following condition : msgType < 0");
			}
			msgId = reader.ReadShort();
			if ( msgId < 0 )
			{
				throw new Exception("Forbidden value on msgId = " + msgId + ", it doesn't respect the following condition : msgId < 0");
			}
			int limit = reader.ReadUShort();
			parameters = new string[limit];
			for (int i = 0; i < limit; i++)
			{
				(parameters as string[])[i] = reader.ReadUTF();
			}
		}
	}
}
