// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobExperienceMultiUpdateMessage.xml' the '24/06/2011 12:04:50'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class JobExperienceMultiUpdateMessage : Message
	{
		public const uint Id = 5809;
		public override uint MessageId
		{
			get
			{
				return 5809;
			}
		}
		
		public Types.JobExperience[] experiencesUpdate;
		
		public JobExperienceMultiUpdateMessage()
		{
		}
		
		public JobExperienceMultiUpdateMessage(Types.JobExperience[] experiencesUpdate)
		{
			this.experiencesUpdate = experiencesUpdate;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)experiencesUpdate.Length);
			for (int i = 0; i < experiencesUpdate.Length; i++)
			{
				experiencesUpdate[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			experiencesUpdate = new Types.JobExperience[limit];
			for (int i = 0; i < limit; i++)
			{
				experiencesUpdate[i] = new Types.JobExperience();
				experiencesUpdate[i].Deserialize(reader);
			}
		}
	}
}
