// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobExperienceUpdateMessage.xml' the '15/06/2011 01:38:52'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class JobExperienceUpdateMessage : Message
	{
		public const uint Id = 5654;
		public override uint MessageId
		{
			get
			{
				return 5654;
			}
		}
		
		public Types.JobExperience experiencesUpdate;
		
		public JobExperienceUpdateMessage()
		{
		}
		
		public JobExperienceUpdateMessage(Types.JobExperience experiencesUpdate)
		{
			this.experiencesUpdate = experiencesUpdate;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			experiencesUpdate.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			experiencesUpdate = new Types.JobExperience();
			experiencesUpdate.Deserialize(reader);
		}
	}
}
