// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterNameSuggestionRequestMessage.xml' the '24/06/2011 12:04:47'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class CharacterNameSuggestionRequestMessage : Message
	{
		public const uint Id = 162;
		public override uint MessageId
		{
			get
			{
				return 162;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
