// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterCreationRequestMessage.xml' the '30/06/2011 11:40:10'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class CharacterCreationRequestMessage : Message
	{
		public const uint Id = 160;
		public override uint MessageId
		{
			get
			{
				return 160;
			}
		}
		
		public string name;
		public byte breed;
		public bool sex;
		public IEnumerable<int> colors;
		
		public CharacterCreationRequestMessage()
		{
		}
		
		public CharacterCreationRequestMessage(string name, byte breed, bool sex, IEnumerable<int> colors)
		{
			this.name = name;
			this.breed = breed;
			this.sex = sex;
			this.colors = colors;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(name);
			writer.WriteByte(breed);
			writer.WriteBoolean(sex);
			foreach (var entry in colors)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			name = reader.ReadUTF();
			breed = reader.ReadByte();
			if ( breed < (byte)Enums.BreedEnum.Feca || breed > (byte)Enums.BreedEnum.Zobal )
			{
				throw new Exception("Forbidden value on breed = " + breed + ", it doesn't respect the following condition : breed < (byte)Enums.BreedEnum.Feca || breed > (byte)Enums.BreedEnum.Zobal");
			}
			sex = reader.ReadBoolean();
			colors = new int[6];
			for (int i = 0; i < 6; i++)
			{
				(colors as int[])[i] = reader.ReadInt();
			}
		}
	}
}
