// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ContentPart.xml' the '24/06/2011 12:04:59'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class ContentPart
	{
		public const uint Id = 350;
		public virtual short TypeId
		{
			get
			{
				return 350;
			}
		}
		
		public string id;
		public byte state;
		
		public ContentPart()
		{
		}
		
		public ContentPart(string id, byte state)
		{
			this.id = id;
			this.state = state;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(id);
			writer.WriteByte(state);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			id = reader.ReadUTF();
			state = reader.ReadByte();
			if ( state < 0 )
			{
				throw new Exception("Forbidden value on state = " + state + ", it doesn't respect the following condition : state < 0");
			}
		}
	}
}
