// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartOkTaxCollectorMessage.xml' the '15/06/2011 01:39:05'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeStartOkTaxCollectorMessage : Message
	{
		public const uint Id = 5780;
		public override uint MessageId
		{
			get
			{
				return 5780;
			}
		}
		
		public int collectorId;
		public Types.ObjectItem[] objectsInfos;
		public int goldInfo;
		
		public ExchangeStartOkTaxCollectorMessage()
		{
		}
		
		public ExchangeStartOkTaxCollectorMessage(int collectorId, Types.ObjectItem[] objectsInfos, int goldInfo)
		{
			this.collectorId = collectorId;
			this.objectsInfos = objectsInfos;
			this.goldInfo = goldInfo;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(collectorId);
			writer.WriteUShort((ushort)objectsInfos.Length);
			for (int i = 0; i < objectsInfos.Length; i++)
			{
				objectsInfos[i].Serialize(writer);
			}
			writer.WriteInt(goldInfo);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			collectorId = reader.ReadInt();
			int limit = reader.ReadUShort();
			objectsInfos = new Types.ObjectItem[limit];
			for (int i = 0; i < limit; i++)
			{
				objectsInfos[i] = new Types.ObjectItem();
				objectsInfos[i].Deserialize(reader);
			}
			goldInfo = reader.ReadInt();
			if ( goldInfo < 0 )
			{
				throw new Exception("Forbidden value on goldInfo = " + goldInfo + ", it doesn't respect the following condition : goldInfo < 0");
			}
		}
	}
}
