// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeClearPaymentForCraftMessage.xml' the '30/06/2011 11:40:18'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeClearPaymentForCraftMessage : Message
	{
		public const uint Id = 6145;
		public override uint MessageId
		{
			get
			{
				return 6145;
			}
		}
		
		public byte paymentType;
		
		public ExchangeClearPaymentForCraftMessage()
		{
		}
		
		public ExchangeClearPaymentForCraftMessage(byte paymentType)
		{
			this.paymentType = paymentType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(paymentType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			paymentType = reader.ReadByte();
		}
	}
}
