// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeShopStockMultiMovementRemovedMessage.xml' the '15/06/2011 01:39:04'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeShopStockMultiMovementRemovedMessage : Message
	{
		public const uint Id = 6037;
		public override uint MessageId
		{
			get
			{
				return 6037;
			}
		}
		
		public int[] objectIdList;
		
		public ExchangeShopStockMultiMovementRemovedMessage()
		{
		}
		
		public ExchangeShopStockMultiMovementRemovedMessage(int[] objectIdList)
		{
			this.objectIdList = objectIdList;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectIdList.Length);
			for (int i = 0; i < objectIdList.Length; i++)
			{
				writer.WriteInt(objectIdList[i]);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectIdList = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				objectIdList[i] = reader.ReadInt();
			}
		}
	}
}
