// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartAsVendorMessage.xml' the '15/06/2011 01:39:04'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeStartAsVendorMessage : Message
	{
		public const uint Id = 5775;
		public override uint MessageId
		{
			get
			{
				return 5775;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
