// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartOkCraftMessage.xml' the '22/08/2011 17:23:02'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeStartOkCraftMessage : Message
	{
		public const uint Id = 5813;
		public override uint MessageId
		{
			get
			{
				return 5813;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
