// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeShopStockMultiMovementUpdatedMessage.xml' the '15/06/2011 01:39:04'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeShopStockMultiMovementUpdatedMessage : Message
	{
		public const uint Id = 6038;
		public override uint MessageId
		{
			get
			{
				return 6038;
			}
		}
		
		public Types.ObjectItemToSell[] objectInfoList;
		
		public ExchangeShopStockMultiMovementUpdatedMessage()
		{
		}
		
		public ExchangeShopStockMultiMovementUpdatedMessage(Types.ObjectItemToSell[] objectInfoList)
		{
			this.objectInfoList = objectInfoList;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectInfoList.Length);
			for (int i = 0; i < objectInfoList.Length; i++)
			{
				objectInfoList[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectInfoList = new Types.ObjectItemToSell[limit];
			for (int i = 0; i < limit; i++)
			{
				objectInfoList[i] = new Types.ObjectItemToSell();
				objectInfoList[i].Deserialize(reader);
			}
		}
	}
}
