// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeRequestedMessage.xml' the '03/10/2011 12:47:06'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeRequestedMessage : Message
	{
		public const uint Id = 5522;
		public override uint MessageId
		{
			get
			{
				return 5522;
			}
		}
		
		public sbyte exchangeType;
		
		public ExchangeRequestedMessage()
		{
		}
		
		public ExchangeRequestedMessage(sbyte exchangeType)
		{
			this.exchangeType = exchangeType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(exchangeType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			exchangeType = reader.ReadSByte();
		}
	}
}
