// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeBidHousePriceMessage.xml' the '05/11/2011 17:25:56'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeBidHousePriceMessage : Message
	{
		public const uint Id = 5805;
		public override uint MessageId
		{
			get
			{
				return 5805;
			}
		}
		
		public int genId;
		
		public ExchangeBidHousePriceMessage()
		{
		}
		
		public ExchangeBidHousePriceMessage(int genId)
		{
			this.genId = genId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(genId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			genId = reader.ReadInt();
			if ( genId < 0 )
			{
				throw new Exception("Forbidden value on genId = " + genId + ", it doesn't respect the following condition : genId < 0");
			}
		}
	}
}
