// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FriendsGetListMessage.xml' the '05/11/2011 17:25:54'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class FriendsGetListMessage : Message
	{
		public const uint Id = 4001;
		public override uint MessageId
		{
			get
			{
				return 4001;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
