// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildMemberWarnOnConnectionStateMessage.xml' the '15/06/2011 01:38:58'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuildMemberWarnOnConnectionStateMessage : Message
	{
		public const uint Id = 6160;
		public override uint MessageId
		{
			get
			{
				return 6160;
			}
		}
		
		public bool enable;
		
		public GuildMemberWarnOnConnectionStateMessage()
		{
		}
		
		public GuildMemberWarnOnConnectionStateMessage(bool enable)
		{
			this.enable = enable;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(enable);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			enable = reader.ReadBoolean();
		}
	}
}
