// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IgnoredGetListMessage.xml' the '24/01/2012 22:50:47'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class IgnoredGetListMessage : Message
	{
		public const uint Id = 5676;
		public override uint MessageId
		{
			get
			{
				return 5676;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
