// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IgnoredListMessage.xml' the '15/06/2011 01:38:59'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class IgnoredListMessage : Message
	{
		public const uint Id = 5674;
		public override uint MessageId
		{
			get
			{
				return 5674;
			}
		}
		
		public Types.IgnoredInformations[] ignoredList;
		
		public IgnoredListMessage()
		{
		}
		
		public IgnoredListMessage(Types.IgnoredInformations[] ignoredList)
		{
			this.ignoredList = ignoredList;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)ignoredList.Length);
			for (int i = 0; i < ignoredList.Length; i++)
			{
				writer.WriteShort(ignoredList[i].TypeId);
				ignoredList[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			ignoredList = new Types.IgnoredInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				ignoredList[i] = Types.ProtocolTypeManager.GetInstance<Types.IgnoredInformations>(reader.ReadShort());
				ignoredList[i].Deserialize(reader);
			}
		}
	}
}
