// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountReleasedMessage.xml' the '24/01/2012 22:50:42'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class MountReleasedMessage : Message
	{
		public const uint Id = 6308;
		public override uint MessageId
		{
			get
			{
				return 6308;
			}
		}
		
		public double mountId;
		
		public MountReleasedMessage()
		{
		}
		
		public MountReleasedMessage(double mountId)
		{
			this.mountId = mountId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteDouble(mountId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mountId = reader.ReadDouble();
		}
	}
}
