// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeMultiCraftSetCrafterCanUseHisRessourcesMessage.xml' the '30/06/2011 11:40:19'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeMultiCraftSetCrafterCanUseHisRessourcesMessage : Message
	{
		public const uint Id = 6021;
		public override uint MessageId
		{
			get
			{
				return 6021;
			}
		}
		
		public bool allow;
		
		public ExchangeMultiCraftSetCrafterCanUseHisRessourcesMessage()
		{
		}
		
		public ExchangeMultiCraftSetCrafterCanUseHisRessourcesMessage(bool allow)
		{
			this.allow = allow;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(allow);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			allow = reader.ReadBoolean();
		}
	}
}
