// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectsQuantityMessage.xml' the '15/06/2011 01:39:07'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ObjectsQuantityMessage : Message
	{
		public const uint Id = 6206;
		public override uint MessageId
		{
			get
			{
				return 6206;
			}
		}
		
		public Types.ObjectItemQuantity[] objectsUIDAndQty;
		
		public ObjectsQuantityMessage()
		{
		}
		
		public ObjectsQuantityMessage(Types.ObjectItemQuantity[] objectsUIDAndQty)
		{
			this.objectsUIDAndQty = objectsUIDAndQty;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectsUIDAndQty.Length);
			for (int i = 0; i < objectsUIDAndQty.Length; i++)
			{
				objectsUIDAndQty[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectsUIDAndQty = new Types.ObjectItemQuantity[limit];
			for (int i = 0; i < limit; i++)
			{
				objectsUIDAndQty[i] = new Types.ObjectItemQuantity();
				objectsUIDAndQty[i].Deserialize(reader);
			}
		}
	}
}
