// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectErrorMessage.xml' the '09/12/2011 21:48:36'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ObjectErrorMessage : Message
	{
		public const uint Id = 3004;
		public override uint MessageId
		{
			get
			{
				return 3004;
			}
		}
		
		public sbyte reason;
		
		public ObjectErrorMessage()
		{
		}
		
		public ObjectErrorMessage(sbyte reason)
		{
			this.reason = reason;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(reason);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			reason = reader.ReadSByte();
		}
	}
}
