// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectsDeletedMessage.xml' the '24/06/2011 12:04:55'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ObjectsDeletedMessage : Message
	{
		public const uint Id = 6034;
		public override uint MessageId
		{
			get
			{
				return 6034;
			}
		}
		
		public int[] objectUID;
		
		public ObjectsDeletedMessage()
		{
		}
		
		public ObjectsDeletedMessage(int[] objectUID)
		{
			this.objectUID = objectUID;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectUID.Length);
			for (int i = 0; i < objectUID.Length; i++)
			{
				writer.WriteInt(objectUID[i]);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectUID = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				objectUID[i] = reader.ReadInt();
			}
		}
	}
}
