// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildModificationStartedMessage.xml' the '26/06/2012 18:47:55'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuildModificationStartedMessage : Message
	{
		public const uint Id = 6324;
		public override uint MessageId
		{
			get
			{
				return 6324;
			}
		}
		
		public bool canChangeName;
		public bool canChangeEmblem;
		
		public GuildModificationStartedMessage()
		{
		}
		
		public GuildModificationStartedMessage(bool canChangeName, bool canChangeEmblem)
		{
			this.canChangeName = canChangeName;
			this.canChangeEmblem = canChangeEmblem;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			byte flag1 = 0;
			flag1 = BooleanByteWrapper.SetFlag(flag1, 0, canChangeName);
			flag1 = BooleanByteWrapper.SetFlag(flag1, 1, canChangeEmblem);
			writer.WriteByte(flag1);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			byte flag1 = reader.ReadByte();
			canChangeName = BooleanByteWrapper.GetFlag(flag1, 0);
			canChangeEmblem = BooleanByteWrapper.GetFlag(flag1, 1);
		}
	}
}
