// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInformationsMembersMessage.xml' the '24/06/2011 12:04:52'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuildInformationsMembersMessage : Message
	{
		public const uint Id = 5558;
		public override uint MessageId
		{
			get
			{
				return 5558;
			}
		}
		
		public Types.GuildMember[] members;
		
		public GuildInformationsMembersMessage()
		{
		}
		
		public GuildInformationsMembersMessage(Types.GuildMember[] members)
		{
			this.members = members;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)members.Length);
			for (int i = 0; i < members.Length; i++)
			{
				members[i].Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			members = new Types.GuildMember[limit];
			for (int i = 0; i < limit; i++)
			{
				members[i] = new Types.GuildMember();
				members[i].Deserialize(reader);
			}
		}
	}
}
