// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyInvitationCancelledForGuestMessage.xml' the '24/06/2011 12:04:51'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyInvitationCancelledForGuestMessage : Message
	{
		public const uint Id = 6256;
		public override uint MessageId
		{
			get
			{
				return 6256;
			}
		}
		
		public int partyId;
		public int cancelerId;
		
		public PartyInvitationCancelledForGuestMessage()
		{
		}
		
		public PartyInvitationCancelledForGuestMessage(int partyId, int cancelerId)
		{
			this.partyId = partyId;
			this.cancelerId = cancelerId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(partyId);
			writer.WriteInt(cancelerId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			partyId = reader.ReadInt();
			if ( partyId < 0 )
			{
				throw new Exception("Forbidden value on partyId = " + partyId + ", it doesn't respect the following condition : partyId < 0");
			}
			cancelerId = reader.ReadInt();
			if ( cancelerId < 0 )
			{
				throw new Exception("Forbidden value on cancelerId = " + cancelerId + ", it doesn't respect the following condition : cancelerId < 0");
			}
		}
	}
}
