// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyLeaderUpdateMessage.xml' the '22/08/2011 17:22:57'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyLeaderUpdateMessage : Message
	{
		public const uint Id = 5578;
		public override uint MessageId
		{
			get
			{
				return 5578;
			}
		}
		
		public int partyLeaderId;
		
		public PartyLeaderUpdateMessage()
		{
		}
		
		public PartyLeaderUpdateMessage(int partyLeaderId)
		{
			this.partyLeaderId = partyLeaderId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(partyLeaderId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			partyLeaderId = reader.ReadInt();
			if ( partyLeaderId < 0 )
			{
				throw new Exception("Forbidden value on partyLeaderId = " + partyLeaderId + ", it doesn't respect the following condition : partyLeaderId < 0");
			}
		}
	}
}
