// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyRestrictedMessage.xml' the '15/06/2011 01:38:54'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyRestrictedMessage : Message
	{
		public const uint Id = 6175;
		public override uint MessageId
		{
			get
			{
				return 6175;
			}
		}
		
		public bool restricted;
		
		public PartyRestrictedMessage()
		{
		}
		
		public PartyRestrictedMessage(bool restricted)
		{
			this.restricted = restricted;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(restricted);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			restricted = reader.ReadBoolean();
		}
	}
}
