// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyAcceptInvitationMessage.xml' the '15/06/2011 01:38:54'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyAcceptInvitationMessage : Message
	{
		public const uint Id = 5580;
		public override uint MessageId
		{
			get
			{
				return 5580;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
