// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PrismBalanceResultMessage.xml' the '15/06/2011 01:39:08'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PrismBalanceResultMessage : Message
	{
		public const uint Id = 5841;
		public override uint MessageId
		{
			get
			{
				return 5841;
			}
		}
		
		public byte totalBalanceValue;
		public byte subAreaBalanceValue;
		
		public PrismBalanceResultMessage()
		{
		}
		
		public PrismBalanceResultMessage(byte totalBalanceValue, byte subAreaBalanceValue)
		{
			this.totalBalanceValue = totalBalanceValue;
			this.subAreaBalanceValue = subAreaBalanceValue;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(totalBalanceValue);
			writer.WriteByte(subAreaBalanceValue);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			totalBalanceValue = reader.ReadByte();
			if ( totalBalanceValue < 0 )
			{
				throw new Exception("Forbidden value on totalBalanceValue = " + totalBalanceValue + ", it doesn't respect the following condition : totalBalanceValue < 0");
			}
			subAreaBalanceValue = reader.ReadByte();
			if ( subAreaBalanceValue < 0 )
			{
				throw new Exception("Forbidden value on subAreaBalanceValue = " + subAreaBalanceValue + ", it doesn't respect the following condition : subAreaBalanceValue < 0");
			}
		}
	}
}
