// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'EntityDispositionInformations.xml' the '14/06/2011 11:32:45'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class EntityDispositionInformations
	{
		public const uint Id = 60;
		public short TypeId
		{
			get
			{
				return 60;
			}
		}
		
		public short cellId;
		public byte direction;
		
		public EntityDispositionInformations()
		{
		}
		
		public EntityDispositionInformations(short cellId, byte direction)
		{
			this.cellId = cellId;
			this.direction = direction;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteShort(cellId);
			writer.WriteByte(direction);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			cellId = reader.ReadShort();
			if ( cellId < -1 || cellId > 559 )
			{
				throw new Exception("Forbidden value on cellId = " + cellId + ", it doesn't respect the following condition : cellId < -1 || cellId > 559");
			}
			direction = reader.ReadByte();
			if ( direction < 0 )
			{
				throw new Exception("Forbidden value on direction = " + direction + ", it doesn't respect the following condition : direction < 0");
			}
		}
	}
}
