// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NetworkDataContainerMessage.xml' the '15/06/2011 01:38:38'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class NetworkDataContainerMessage : Message
	{
		public const uint Id = 6240;
		public override uint MessageId
		{
			get
			{
				return 6240;
			}
		}
		
		public byte[] content;
		
		public NetworkDataContainerMessage()
		{
		}
		
		public NetworkDataContainerMessage(byte[] content)
		{
			this.content = content;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)content.Length);
			for (int i = 0; i < content.Length; i++)
			{
				writer.WriteByte(content[i]);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			content = new byte[limit];
			for (int i = 0; i < limit; i++)
			{
				content[i] = reader.ReadByte();
			}
		}
	}
}
