// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PrismSubAreaInformation.xml' the '24/06/2011 12:04:59'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class PrismSubAreaInformation
	{
		public const uint Id = 142;
		public virtual short TypeId
		{
			get
			{
				return 142;
			}
		}
		
		public int subId;
		public byte alignment;
		public short worldX;
		public short worldY;
		public int mapId;
		public bool isInFight;
		public bool isFightable;
		
		public PrismSubAreaInformation()
		{
		}
		
		public PrismSubAreaInformation(int subId, byte alignment, short worldX, short worldY, int mapId, bool isInFight, bool isFightable)
		{
			this.subId = subId;
			this.alignment = alignment;
			this.worldX = worldX;
			this.worldY = worldY;
			this.mapId = mapId;
			this.isInFight = isInFight;
			this.isFightable = isFightable;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(subId);
			writer.WriteByte(alignment);
			writer.WriteShort(worldX);
			writer.WriteShort(worldY);
			writer.WriteInt(mapId);
			writer.WriteBoolean(isInFight);
			writer.WriteBoolean(isFightable);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			subId = reader.ReadInt();
			if ( subId < 0 )
			{
				throw new Exception("Forbidden value on subId = " + subId + ", it doesn't respect the following condition : subId < 0");
			}
			alignment = reader.ReadByte();
			if ( alignment < 0 )
			{
				throw new Exception("Forbidden value on alignment = " + alignment + ", it doesn't respect the following condition : alignment < 0");
			}
			worldX = reader.ReadShort();
			if ( worldX < -255 || worldX > 255 )
			{
				throw new Exception("Forbidden value on worldX = " + worldX + ", it doesn't respect the following condition : worldX < -255 || worldX > 255");
			}
			worldY = reader.ReadShort();
			if ( worldY < -255 || worldY > 255 )
			{
				throw new Exception("Forbidden value on worldY = " + worldY + ", it doesn't respect the following condition : worldY < -255 || worldY > 255");
			}
			mapId = reader.ReadInt();
			isInFight = reader.ReadBoolean();
			isFightable = reader.ReadBoolean();
		}
	}
}
