// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TaxCollectorHireRequestMessage.xml' the '15/06/2011 01:39:01'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class TaxCollectorHireRequestMessage : Message
	{
		public const uint Id = 5681;
		public override uint MessageId
		{
			get
			{
				return 5681;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
