// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NpcGenericActionFailureMessage.xml' the '26/06/2012 18:47:51'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class NpcGenericActionFailureMessage : Message
	{
		public const uint Id = 5900;
		public override uint MessageId
		{
			get
			{
				return 5900;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
