// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DisplayNumericalValueMessage.xml' the '30/06/2011 11:40:11'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class DisplayNumericalValueMessage : Message
	{
		public const uint Id = 5808;
		public override uint MessageId
		{
			get
			{
				return 5808;
			}
		}
		
		public int entityId;
		public int value;
		public byte type;
		
		public DisplayNumericalValueMessage()
		{
		}
		
		public DisplayNumericalValueMessage(int entityId, int value, byte type)
		{
			this.entityId = entityId;
			this.value = value;
			this.type = type;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(entityId);
			writer.WriteInt(value);
			writer.WriteByte(type);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			entityId = reader.ReadInt();
			value = reader.ReadInt();
			type = reader.ReadByte();
			if ( type < 0 )
			{
				throw new Exception("Forbidden value on type = " + type + ", it doesn't respect the following condition : type < 0");
			}
		}
	}
}
