// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayDelayedActionFinishedMessage.xml' the '15/06/2011 01:38:50'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameRolePlayDelayedActionFinishedMessage : Message
	{
		public const uint Id = 6150;
		public override uint MessageId
		{
			get
			{
				return 6150;
			}
		}
		
		public byte delayTypeId;
		
		public GameRolePlayDelayedActionFinishedMessage()
		{
		}
		
		public GameRolePlayDelayedActionFinishedMessage(byte delayTypeId)
		{
			this.delayTypeId = delayTypeId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(delayTypeId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			delayTypeId = reader.ReadByte();
			if ( delayTypeId < 0 )
			{
				throw new Exception("Forbidden value on delayTypeId = " + delayTypeId + ", it doesn't respect the following condition : delayTypeId < 0");
			}
		}
	}
}
