// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayDelayedActionMessage.xml' the '24/06/2011 12:04:49'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameRolePlayDelayedActionMessage : Message
	{
		public const uint Id = 6153;
		public override uint MessageId
		{
			get
			{
				return 6153;
			}
		}
		
		public byte delayTypeId;
		public int delayDuration;
		
		public GameRolePlayDelayedActionMessage()
		{
		}
		
		public GameRolePlayDelayedActionMessage(byte delayTypeId, int delayDuration)
		{
			this.delayTypeId = delayTypeId;
			this.delayDuration = delayDuration;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(delayTypeId);
			writer.WriteInt(delayDuration);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			delayTypeId = reader.ReadByte();
			if ( delayTypeId < 0 )
			{
				throw new Exception("Forbidden value on delayTypeId = " + delayTypeId + ", it doesn't respect the following condition : delayTypeId < 0");
			}
			delayDuration = reader.ReadInt();
			if ( delayDuration < 0 )
			{
				throw new Exception("Forbidden value on delayDuration = " + delayDuration + ", it doesn't respect the following condition : delayDuration < 0");
			}
		}
	}
}
