// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DownloadGetCurrentSpeedRequestMessage.xml' the '15/06/2011 01:39:10'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Messages
{
	public class DownloadGetCurrentSpeedRequestMessage : Message
	{
		public const uint Id = 1510;
		public override uint MessageId
		{
			get
			{
				return 1510;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
