// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeleportBuddiesAnswerMessage.xml' the '03/10/2011 12:47:05'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class TeleportBuddiesAnswerMessage : Message
	{
		public const uint Id = 6294;
		public override uint MessageId
		{
			get
			{
				return 6294;
			}
		}
		
		public bool accept;
		
		public TeleportBuddiesAnswerMessage()
		{
		}
		
		public TeleportBuddiesAnswerMessage(bool accept)
		{
			this.accept = accept;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(accept);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			accept = reader.ReadBoolean();
		}
	}
}
