// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'LockableCodeResultMessage.xml' the '26/06/2012 18:47:50'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class LockableCodeResultMessage : Message
	{
		public const uint Id = 5672;
		public override uint MessageId
		{
			get
			{
				return 5672;
			}
		}
		
		public sbyte result;
		
		public LockableCodeResultMessage()
		{
		}
		
		public LockableCodeResultMessage(sbyte result)
		{
			this.result = result;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(result);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			result = reader.ReadSByte();
			if ( result < 0 )
			{
				throw new Exception("Forbidden value on result = " + result + ", it doesn't respect the following condition : result < 0");
			}
		}
	}
}
