// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutObjectItem.xml' the '14/06/2011 11:32:50'
using System;
using Stump.BaseCore.Framework.IO;

namespace Stump.DofusProtocol.Types
{
	public class ShortcutObjectItem : ShortcutObject
	{
		public const uint Id = 371;
		public short TypeId
		{
			get
			{
				return 371;
			}
		}
		
		public int itemUID;
		
		public ShortcutObjectItem()
		{
		}
		
		public ShortcutObjectItem(int slot, int itemUID)
			 : base(slot)
		{
			this.itemUID = itemUID;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(itemUID);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			itemUID = reader.ReadInt();
		}
	}
}
