// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutSmiley.xml' the '26/06/2012 18:48:04'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class ShortcutSmiley : Shortcut
	{
		public const uint Id = 388;
		public override short TypeId
		{
			get
			{
				return 388;
			}
		}
		
		public sbyte smileyId;
		
		public ShortcutSmiley()
		{
		}
		
		public ShortcutSmiley(int slot, sbyte smileyId)
			 : base(slot)
		{
			this.smileyId = smileyId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteSByte(smileyId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			smileyId = reader.ReadSByte();
			if ( smileyId < 0 )
			{
				throw new Exception("Forbidden value on smileyId = " + smileyId + ", it doesn't respect the following condition : smileyId < 0");
			}
		}
	}
}
