// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutObjectPreset.xml' the '24/06/2011 12:04:59'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class ShortcutObjectPreset : ShortcutObject
	{
		public const uint Id = 370;
		public override short TypeId
		{
			get
			{
				return 370;
			}
		}
		
		public byte presetId;
		
		public ShortcutObjectPreset()
		{
		}
		
		public ShortcutObjectPreset(int slot, byte presetId)
			 : base(slot)
		{
			this.presetId = presetId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteByte(presetId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			presetId = reader.ReadByte();
			if ( presetId < 0 )
			{
				throw new Exception("Forbidden value on presetId = " + presetId + ", it doesn't respect the following condition : presetId < 0");
			}
		}
	}
}
